In [3]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(type(a))

<class 'numpy.ndarray'>


In [9]:
a = np.arange(1,11)
a
print(type(a))

<class 'numpy.ndarray'>


In [21]:
b=np.zeros((3,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [27]:
b=np.ones((3,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [31]:
c=np.linspace(1,10,10)
c

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [35]:
d=np.eye(5)
d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
import random
e=np.random.randint(1,101,10)
e

array([16, 43, 98, 23, 69, 20, 44,  6, 37, 36])

In [45]:
f=np.sort(e)
f

array([ 6, 16, 20, 23, 36, 37, 43, 44, 69, 98])

In [47]:
print(f.min())

6


In [49]:
print(f.max())

98


In [51]:
print(f.mean())

39.2


In [53]:
print(f.std())

25.825568725586663


In [55]:
g= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
g.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [61]:
h=g
print(h+5)
'''for i in h:
    print(i+5)'''

[ 6  7  8  9 10 11 12 13 14 15 16 17]


'for i in h:\n    print(i+5)'

In [65]:
h
print(h*2)

[ 2  4  6  8 10 12 14 16 18 20 22 24]


In [69]:
i = np.array([1,2,3,4])
j= np.array([5,6,7,8])
print(i+j)

[ 6  8 10 12]


In [71]:
i = np.array([1,2,3,4])
j= np.array([5,6,7,8])
print(i-j)

[-4 -4 -4 -4]


In [73]:
i = np.array([1,2,3,4])
j= np.array([5,6,7,8])
print(i*j)

[ 5 12 21 32]


In [83]:
i = np.array([1,2,3,4])
j= np.array([5,6,7,8])
k= i*j
k
total=0
for i in k:
    total=total+i
print(total)

70


In [91]:
k=np.dot(i,j)
k

array([160, 192, 224, 256])

In [95]:
l=np.array([1,2,3,4,5,6,7,8])
print(l[:3])

[1 2 3]


In [97]:
print(l[-3:])

[6 7 8]


In [109]:
print(l[3:])

[4 5 6 7 8]
