In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)
print(type(a))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))
np.ndim(a)

[1 2 3 4 5]
<class 'numpy.ndarray'>


1

In [15]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)
np.shape(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


(2, 5)

In [17]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)
np.size(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


10